### ISSUE TITLE
[Colaboração Projeto] Enviar um POST para endpoint do Cola?Bora solicitando um convite para projeto

### ISSUE THREAD

**Issue by eliseuramos93** [TreinaDev/td11-portfoliorrr#120]
### User Story
Como uma aplicação integrada ao Cola?Bora!, quero enviar uma requisição de solicitação de convite de projeto à plataforma co-irmã, para proporcionar aos meus usuários uma experiência fluida quando eles procuram projetos para colaborar.

### Critérios de Aceite
- [x] Ao criar um `invitation_request` em nosso banco de dados, enfileirar um job em `RequestInvitationJob` e passar uma mensagem de sucesso ao cliente;
- [x] Ao executar o job, enviar uma requisição POST para `POST /api/v1/proposals` para criar um `proposal` no Cola?Bora!
  - [x] Se recebermos uma resposta status `201` do Cola?Bora!, alterar o status de `invitation_request` para `pending`
  - [x] Se recebemos uma resposta status `4XX` do Cola?Bora!, `invitation_request` vai pro status  `error`;
  - [x] Se recebermos uma resposta status `500` do Cola?Bora!, criar um novo job em `RequestInvitationJob` para novas tentativas; 
    - [x] Cada tentativa deve ter um intervalo de 1 hora em relação à última;
    - [x] Se a tentativa retornar `201` ou `4XX`, não devem ser feitas novas requisições;
    - [x] Se a tentativa retornar `500`, enfileirar um novo job até um máximo de 5 tentativas contando com a inicial
       - [x] Na 5ª tentativa, se ainda recebermos uma resposta com status `500`, alterar status de `invitation_request` para `aborted` e parar de enfileirar jobs para esse `invitation_request`
- [x] Não mostrar ao usuário em nenhum lugar que foi feita uma requisição API ao Cola?Bora!
- [x] Caso a API do Portfoliorrr esteja fora do ar, criar um novo job (sem limites de tentativa) para enviar nova requisição à nossa própria API novamente 1 hora depois 

#### Status de solicitações de convite (enum)
  - 0: `processing` => `invitation_request` criado no Portfoliorrr, ainda não criado no ColaBora
  - 5: `pending` => `invitation_request` criado no Portfoliorrr, criado no ColaBora (proposal) via POST
  - 10: `accepted` => `invitation_request` aceito pelo líder de projeto no ColaBora, usuário receberá um convite para o projeto
  - 15: `refused`  => `invitation_request` recusado pelo líder de projeto no ColaBora
  - 20: `error` => recebemos um erro `4XX` ao tentar criar um proposal no ColaBora
  - 25: `aborted` => tentamos criar um proposal 5x no ColaBora, e em todas recebemos `500`. Não faremos mais requisições ao Cola?Bora!

### Débitos
- Usuário não consegue criar nova solicitação de convite em caso de status `aborted`, `error` ou `refused`. Isso precisa ser alterado em PR futura.

**Comment by eliseuramos93** [comment]
- [ ] Precisamos de um atributo `status` para `invitation_request` para monitorar a situação do pedido de convite;
- [ ] Pode ser necessário um job para ficar tentando obter uma resposta da API do Cola?Bora! de tempos em tempos (tbd) caso a primeira requisição aconteça com o CB fora do ar;
- [ ] Já existe um [card no Cola?Bora!](https://github.com/orgs/TreinaDev/projects/21?pane=issue&itemId=52446975) para o líder de projeto recusar uma solicitação de convite

**Comment by paulohenrique-gh** [comment]
Comentando aqui só pra não esquecer. Tentei rodar as duas aplicações e o Colabora não salva a solicitação porque pra eles o atributo invitation_request_id está como portfoliorrr_proposal_id

ProposalsController no Colabora
![Image](https://github.com/TreinaDev/td11-portfoliorrr/assets/124916478/c7b03059-1fb2-46b7-8900-1ceb3cbc20d0)

Dados que o Portfoliorrr está enviando
![Image](https://github.com/TreinaDev/td11-portfoliorrr/assets/124916478/252cc2fc-68f3-4dfe-ad46-1f952b481492)

JSON que estão retornando
![Image](https://github.com/TreinaDev/td11-portfoliorrr/assets/124916478/e2734c3f-4221-478b-87d9-03a419377435)

Status na página de solicitações no Portfoliorrr
![Image](https://github.com/TreinaDev/td11-portfoliorrr/assets/124916478/e9e38b87-952a-4a81-8a6a-8bb8869cc3ff)
