### ISSUE TITLE
[Categorias] Usuário administrador cria categorias de trabalho

### ISSUE THREAD

**Issue by gmkoeb** [TreinaDev/td11-portfoliorrr#13]
## User Story
Como um usuário administrador, quero criar categorias de trabalhos na plataforma, para que usuários possam listá-las em seus perfis profissionais e com isso encontrem projetos que possuam sinergia com suas habilidades

## Critérios de aceite
- [x] somente usuário admin pode criar categorias

**Comment by hreis1** [comment]
- [ ] somente usuário admin pode criar categorias
